### PR TITLE
Update to kernel 6.10.2

### PR DESCRIPTION
**Pull request by RononDex**
Tested on my machine, kernel compiles and installs fine, took current config from 6.8.2 Arch Linux

```
❯ uname -a
Linux ATLANTIS-LAB 6.8.2-arch1-1-vivepro2 #1 SMP PREEMPT_DYNAMIC Fri, 05 Apr 2024 08:06:36 +0000 x86_64 GNU/Linux
```

### CODE REVIEW

**Comment by RononDex** [comment]
Also added a .gitignore to ignore build files in the kernel directory

**Comment by WorldofShadows** [comment]
Hey! :)
just here to thank you. 
Took your 6.8.7 files as an example and compiled 6.9.3 just fine including the kernel patches as an absolute first timer in kernel building :) 
Installed and runs fine with basic stress testing.

Just have no idea how to commit anything here. Never done that before.

`uname -a
Linux hyperion 6.9.3-arch1-1-vivepro2 #1 SMP PREEMPT_DYNAMIC Sun, 02 Jun 2024 17:32:15 +0000 x86_64 GNU/Linux`

**Comment by RononDex** [comment]
Hey, you can fort my repository (button on the top right if you have my github repository open), then clone your repository, commit and push and create a pull request if you want the changes to be merged into my or the original repository.

I update this repository from time to time, since I dont want to use extremly old linux kernels :D 
Original author does not seem to care about updating to newer kernel versions more often it seems.

**Comment by WorldofShadows** [comment]
Nice, will do that and do a pull request with your repo then :)
Another short question:
According to https://github.com/CertainLach/VivePro2-Linux-Driver Patch 1 and 2 are already in the kernel, so maybe we can leave those out and only apply Patch 3. What do you think?

**Comment by HavenOfTheRaven** [comment]
From what I can tell the two patches that were merged in 5.18 are different from the other kernel patches that are included here. I checked the kernel source code and they have still not been merged, although I have heard that CertainLach is trying to get them merged into the mainline kernel.

**Comment by RononDex** [comment]
> Nice, will do that and do a pull request with your repo then :) Another short question: According to https://github.com/CertainLach/VivePro2-Linux-Driver Patch 1 and 2 are already in the kernel, so maybe we can leave those out and only apply Patch 3. What do you think?

Yes I noticed that and tried leaving them out, however something didnt work out (cant remember what exactly) which is why I let them the way they were.

**Comment by WorldofShadows** [comment]
Got it. :) 
I left them in my build just as you did, just was curious. 
Got everything up and pull request is out :)

**Comment by santeri3700** [comment]
Hi, sorry for the radio silence! I haven't had much time to focus on this project or VR in general.
Thank you for the contribution! First time seeing a Satedan here on GitHub ;)

**Pull request merged**
